export const Books = [
	{
		price: 12.25,
		id: "1912047918",
		title: "Create Graphical User Interfaces with Python",
		subtitle: "How to build windows, buttons, and widgets for your Python projects",
		authors: "Martin O&#039;Hanlon, Laura Sach",
		image: "https://www.dbooks.org/img/books/1912047918s.jpg",
		url: "https://www.dbooks.org/create-graphical-user-interfaces-with-python-1912047918/",
	},
	{
		price: 7.9,
		id: "3319524623",
		title: "Solving PDEs in Python",
		subtitle: "The FEniCS Tutorial I",
		authors: "Hans Petter Langtangen, Anders Logg",
		image: "https://www.dbooks.org/img/books/3319524623s.jpg",
		url: "https://www.dbooks.org/solving-pdes-in-python-3319524623/",
	},
	{
		id: "1503212300",
		price: 29,
		title: "Invent Your Own Computer Games with Python",
		subtitle: "A beginner's guide to computer programming in Python",
		authors: "Al Sweigart",
		image: "https://www.dbooks.org/img/books/1503212300s.jpg",
		url: "https://www.dbooks.org/invent-your-own-computer-games-with-python-1503212300/",
	},
	{
		id: "1098127463",
		price: 19,
		soldOut: false,
		title: "Security as Code",
		subtitle: "DevSecOps Patterns with AWS",
		authors: "BK Sarthak Das, Virginia Chu",
		image: "https://www.dbooks.org/img/books/1098127463s.jpg",
		url: "https://www.dbooks.org/security-as-code-1098127463/",
	},
	{
		id: "1805112015",
		price: 29,
		soldOut: false,
		title: "Financing Investment in Times of High Public Debt",
		subtitle: "2023 European Public Investment Outlook",
		authors: "Floriana Cerniglia, Francesco Saraceno, Andrew Watt",
		image: "https://www.dbooks.org/img/books/1805112015s.jpg",
		url: "https://www.dbooks.org/financing-investment-in-times-of-high-public-debt-1805112015/",
	},
];
